---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: helm-sub-release
spec:
  interval: 5m
  chart:
    spec:
      chart: charts/testsubchart
      sourceRef:
        kind: GitRepository
        name: test-repo

