apiVersion: source.toolkit.fluxcd.io/v1
kind: GitRepository
metadata:
  name: test-repo
  namespace: default
spec:
  interval: 5m
  url: https://github.com/dledanseur/testflux.git
  ref:
    branch: main

