---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: helm-release
  namespace: default
spec:
  interval: 5m
  chart:
    spec:
      chart: charts/testchart
      sourceRef:
        kind: GitRepository
        name: test-repo

